#!/bin/bash -e

command_args=${@:2}
command_name=$1
image_name="chronicles"
image_workdir="/chronicles"

case "$command_name" in
  setup)
    docker build \
      --build-arg uid="$UID" \
      --build-arg workdir="$image_workdir" \
      -t "$image_name" .
  ;;

  bash)
    docker run --rm -it -v "$PWD":"$image_workdir" -p "40000:40000" "$image_name"
  ;;

  run)
    echo "Bringing server up! Listening on 0.0.0.0:40000"
    docker run --rm -it \
      -v "$PWD":"$image_workdir" \
      -p "40000:40000" \
      "$image_name" \
      bin/run
  ;;
esac
